package com.plainly.driver.jdbc.dialect;

import com.plainly.driver.TypeCategory;
import com.plainly.driver.ddl.ColumnDraft;
import com.plainly.driver.ddl.TableChange;
import com.plainly.driver.meta.DbObjects.ColumnInfo;

import java.util.List;

/**
 * Oracle。
 *
 * <p>它和前面几家的差别不在个别关键字，而在几处<b>写错了才发现</b>的地方：
 *
 * <ul>
 *   <li><b>列定义里 DEFAULT 必须排在 NOT NULL 前面。</b>标准写法
 *       {@code c NUMBER NOT NULL DEFAULT 0} 在 Oracle 上是 ORA-00907，
 *       报的还是「缺少右括号」这种看不出所以然的错；</li>
 *   <li><b>改列是一条 {@code MODIFY}，不是三条 {@code ALTER COLUMN}。</b>
 *       而且 {@code MODIFY (c NOT NULL)} 打在本来就非空的列上会报 ORA-01442，
 *       所以可空性只在<b>真的变了</b>的时候才写出来；</li>
 *   <li><b>没有 {@code INFORMATION_SCHEMA}。</b>触发器和视图定义分别在
 *       {@code ALL_TRIGGERS} 和 {@code ALL_VIEWS} 里，列名也另一套；</li>
 *   <li><b>「库」不是 schema。</b>一个实例里的 schema 才对应别家的库，
 *       而 schema 就是用户——所以建库这件事在这里等于建用户，见
 *       {@link #schemaCreationUnsupportedReason()}。</li>
 * </ul>
 *
 * <h2>分页用的是 12c 起的 OFFSET/FETCH</h2>
 * 11g 及更早只能用 {@code ROWNUM} 套三层子查询，而那种写法会在结果集里多出一列
 * {@code RN}——本工具在这一层拿不到列名，没法把它排除掉，多出来的列会跟着进网格，
 * 还会让「同源单表」的可编辑判定失效。与其生成一条看着能跑、实际把界面弄坏的语句，
 * 不如只支持 12c 起的写法，并在连上 11g 时于状态栏如实说明（见
 * {@code JdbcConnection#readServerVersion}）。
 */
public class OracleDialect extends Dialects.StandardDialect {

    // ------------------------------------------------------------------ 分页

    /**
     * {@code OFFSET n ROWS FETCH NEXT m ROWS ONLY}。
     *
     * <p>两个参数都不给时返回空串，而不是 {@code OFFSET 0 ROWS}：
     * 带筛选的计数是把分页查询的 WHERE 段剪下来拼成 COUNT 的，
     * 剪的判据是找 {@code " LIMIT "}——找不到就整段留着。留一条
     * {@code OFFSET 0 ROWS} 在 COUNT 后面虽然 Oracle 忍得下，但没有意义，
     * 而且换个库就是语法错误。这里直接不产出它。
     */
    @Override
    public String limitOffset(int limit, int offset) {
        StringBuilder sb = new StringBuilder();
        if (offset > 0) {
            sb.append("OFFSET ").append(offset).append(" ROWS");
        }
        if (limit > 0) {
            if (sb.length() > 0) {
                sb.append(' ');
            }
            sb.append("FETCH NEXT ").append(limit).append(" ROWS ONLY");
        }
        return sb.toString();
    }

    // ------------------------------------------------------------------ 列定义

    /**
     * 自增列的写法，接在列定义末尾。
     *
     * <p>Oracle 12.1 起支持 SQL 标准的 {@code GENERATED BY DEFAULT AS IDENTITY}。
     * 用 BY DEFAULT 而不是 ALWAYS：后者<b>禁止</b>显式插入这一列，
     * 而「复制表并带数据」正是要把源表的主键值原样写过去——
     * 用 ALWAYS 的话那条 INSERT 会被数据库直接拒绝。
     *
     * <p>子类（达梦）改写这一段。
     */
    protected String identityClause() {
        return " GENERATED BY DEFAULT AS IDENTITY";
    }

    /**
     * 计数器仍然要自己调，所以这里返回 null。
     *
     * <p>Oracle 改种子要 {@code ALTER TABLE ... MODIFY (c GENERATED ... START WITH LIMIT VALUE)}，
     * 12.2 起才有，而 H2 的 Oracle 兼容模式跑不了这一句——也就是说没有任何办法验证它。
     * 发一条没跑过的语句，失败会发生在「复制表」已经把数据灌完之后，
     * 比不发更难收拾。返回 null 时界面会明说「计数器要自己调」。
     */
    @Override
    public String restartAutoIncrementDdl(String schema, String table, String column, long next) {
        return null;
    }

    /**
     * 列定义。顺序是 {@code 名字 类型 [DEFAULT x] [NOT NULL]}。
     *
     * <p>可空时不写 {@code NULL}：Oracle 认这个写法，但列本来就默认可空，
     * 少一个词就少一处出错的地方。
     */
    @Override
    public String columnDefinition(ColumnDraft column) {
        StringBuilder sb = new StringBuilder(quote(column.name())).append(' ')
                .append(column.fullType());

        /*
         * 顺序：类型 -> 身份列 -> 默认值 -> NOT NULL。
         *
         * 这一条是在 Oracle 23ai 实例上撞出来的。原来把身份列子句放在最后，
         * 注释还写着「Oracle 要求 identity 子句在列约束之后」——那句话是错的，
         * 发过去直接 ORA-03076「列定义或内部约束条件中存在意外项 GENERATED」。
         *
         * Oracle 的列定义语法是：
         *   列名 类型 [DEFAULT 表达式 | 身份列子句] [内联约束...]
         * 身份列子句紧跟在类型后面，而 NOT NULL 是<b>内联约束</b>，排在它之后。
         *
         * 还有一条：身份列和 DEFAULT <b>互斥</b>，两个一起写同样报错。
         * 自增列的值由序列给，本来也不该再有默认值。
         */
        boolean identity = column.autoIncrement();
        if (identity) {
            sb.append(identityClause());
        } else if (column.defaultValue() != null && !column.defaultValue().isBlank()) {
            sb.append(" DEFAULT ").append(column.defaultValue());
        }
        if (!column.nullable()) {
            sb.append(" NOT NULL");
        }
        return sb.toString();
    }

    /**
     * Oracle 给的 {@code COLUMN_DEF} 是列上写着的那段字面量原文，
     * 契约本来就对得上；只是它取自一个 LONG 列，常带着尾部空白和换行。
     */
    @Override
    public String normalizeDefault(String raw, TypeCategory category) {
        if (raw == null) {
            return null;
        }
        String trimmed = raw.trim();
        return trimmed.isEmpty() ? null : trimmed;
    }

    // ------------------------------------------------------------------ DDL

    @Override
    public List<TableChangeSql> ddlFor(String schema, String table, TableChange change) {
        String t = qualify(schema, table);
        List<TableChangeSql> out = new java.util.ArrayList<>();

        if (change instanceof TableChange.AddColumn c) {
            out.add(new TableChangeSql(change,
                    "ALTER TABLE " + t + " ADD (" + columnDefinition(c.column()) + ")"));
            addComment(out, change, t, c.column());
            return out;
        }
        if (change instanceof TableChange.RenameColumn c) {
            out.add(new TableChangeSql(change, "ALTER TABLE " + t + " RENAME COLUMN "
                    + quote(c.from().name()) + " TO " + quote(c.to().name())));
            if (c.definitionAlsoChanged()) {
                alterInPlace(out, change, t, c.from(), c.to());
            }
            return out;
        }
        // 删列、改主键、改表名，Oracle 和标准写法一致
        return super.ddlFor(schema, table, change);
    }

    /**
     * 就地改定义：类型、默认值、可空性合成<b>一条</b> {@code MODIFY}。
     *
     * <p>拆成三条不只是啰嗦——Oracle 的每条 DDL 都隐式提交，三条就是三个不可回滚的
     * 提交点，中间失败会把表留在改了一半的状态。
     *
     * <p>可空性只在真的变了的时候写：往已经非空的列上再打一次 {@code NOT NULL}
     * 是 ORA-01442，往已经可空的列上打 {@code NULL} 是 ORA-01451。
     */
    @Override
    protected void alterInPlace(List<TableChangeSql> out, TableChange change, String t,
                                ColumnInfo from, ColumnDraft to) {
        StringBuilder parts = new StringBuilder();
        if (!from.displayType().equalsIgnoreCase(to.fullType())) {
            parts.append(to.fullType());
        }
        if (!sameDefault(from.defaultValue(), to.defaultValue())) {
            append(parts, "DEFAULT " + (to.defaultValue() == null || to.defaultValue().isBlank()
                    ? "NULL" : to.defaultValue()));
        }
        if (from.nullable() != to.nullable()) {
            append(parts, to.nullable() ? "NULL" : "NOT NULL");
        }
        if (parts.length() > 0) {
            out.add(new TableChangeSql(change, "ALTER TABLE " + t + " MODIFY ("
                    + quote(to.name()) + " " + parts + ")"));
        }
        addComment(out, change, t, to);
    }

    private static void append(StringBuilder sb, String piece) {
        if (sb.length() > 0) {
            sb.append(' ');
        }
        sb.append(piece);
    }

    // ------------------------------------------------------------------ 元数据查询

    /**
     * {@code ALL_TABLES.NUM_ROWS} 由 {@code DBMS_STATS} 维护。
     *
     * <p>从没收集过统计信息的表这里是 NULL——那是「不知道」，不是空表，
     * 读的时候按未知处理。Oracle 库上这种情况比 MySQL 常见得多。
     */
    @Override
    public String tableRowCountQuery(String schema) {
        return "SELECT TABLE_NAME, NUM_ROWS FROM ALL_TABLES WHERE OWNER = " + literal(schema);
    }

    /**
     * 触发器在 {@code ALL_TRIGGERS} 里。
     *
     * <p>四列对应「名称、时机、事件、动作」：{@code TRIGGER_TYPE} 是
     * 「BEFORE EACH ROW」这种，{@code TRIGGERING_EVENT} 是「INSERT OR UPDATE」。
     * 注意归属列叫 {@code TABLE_OWNER} 而不是 schema。
     */
    @Override
    public String triggersQuery(String schema, String table) {
        return "SELECT TRIGGER_NAME, TRIGGER_TYPE, TRIGGERING_EVENT, TRIGGER_BODY"
                + " FROM ALL_TRIGGERS"
                + " WHERE TABLE_OWNER = " + literal(schema)
                + " AND TABLE_NAME = " + literal(table)
                + " ORDER BY TRIGGER_NAME";
    }

    /**
     * Oracle 的驱动不报结果集的来源表名。
     *
     * <p>在 Oracle 23ai 上实测：{@code ResultSetMetaData.getTableName()} 对每一列
     * 都返回空串。这不是配置问题，是这个驱动一贯的行为——报表名要额外的往返，
     * 它选择不做。
     */
    @Override
    public boolean reportsResultSetTableNames() {
        return false;
    }

    /**
     * 例程清单。达梦继承这一条——它的数据字典视图和 Oracle 同名同结构
     * （在 DM 8.1.2 上确认过 {@code ALL_SOURCE} 的 NAME / LINE / TEXT 三列都在）。
     *
     * <p>只取 {@code PROCEDURE} 和 {@code FUNCTION}。包（PACKAGE / PACKAGE BODY）
     * 要按「先规范后体」的顺序成对导出才还原得回去，这一版没做，
     * 与其导出一半让人以为齐了，不如不导——备份文件的头部会写明这一点。
     */
    @Override
    public String routineListQuery(String schema) {
        return "SELECT DISTINCT NAME, TYPE FROM ALL_SOURCE"
                + " WHERE OWNER = " + literal(schema)
                + " AND TYPE IN ('PROCEDURE', 'FUNCTION')"
                + " ORDER BY TYPE, NAME";
    }

    /**
     * 源码<b>按行</b>存在 {@code ALL_SOURCE} 里，要按 LINE 拼回去。
     *
     * <p>取出来的第一行是 {@code PROCEDURE 名字(...)}——没有 {@code CREATE} 这个词。
     * 所以调用方拼完之后要自己补上 {@code CREATE OR REPLACE }，
     * 否则那一段在还原时是一句语法错误。这件事由 {@link #routineSourceNeedsCreatePrefix()}
     * 声明，别让每个调用方各猜一次。
     */
    @Override
    public String routineSourceQuery(String schema, String name, String routineType) {
        return "SELECT TEXT FROM ALL_SOURCE"
                + " WHERE OWNER = " + literal(schema)
                + " AND NAME = " + literal(name)
                + " AND TYPE = " + literal(routineType)
                + " ORDER BY LINE";
    }

    @Override
    public boolean routineSourceNeedsCreatePrefix() {
        return true;
    }

    /**
     * Oracle 的触发器名在<b>模式</b>内唯一，不是每张表唯一。达梦继承这一条。
     *
     * <p>它们发的是 {@code CREATE OR REPLACE}，撞名不会报错而是<b>覆盖</b>——
     * 所以这条查询在这两家上更要紧：报错是响的，覆盖是静默的。
     */
    @Override
    public String triggerNameConflictQuery(String schema, String triggerName) {
        return "SELECT TRIGGER_NAME, TABLE_NAME FROM ALL_TRIGGERS"
                + " WHERE OWNER = " + literal(schema)
                + " AND TRIGGER_NAME = " + literal(triggerName);
    }

    /**
     * 序列在数据字典视图 {@code ALL_SEQUENCES} 里，Oracle 没有 information_schema。
     *
     * <p>用 {@code ALL_} 而不是 {@code USER_}：连上来的账号未必就是这个 schema 的属主，
     * 用 USER_ 的话，看别人的 schema 会得到一个空列表——而空列表和「真的没有序列」
     * 在界面上长得一模一样。
     *
     * <p>{@code LAST_NUMBER} 是「下一次会发出去的值」的近似：带 CACHE 的序列上，
     * 它是缓存段的上界而不是实际用到的位置。所以这一列只写进说明文字，
     * 不当作精确值用。
     */
    @Override
    public String sequencesQuery(String schema) {
        return "SELECT SEQUENCE_NAME,"
                + " '当前约 ' || LAST_NUMBER || ' · 步长 ' || INCREMENT_BY"
                + " FROM ALL_SEQUENCES WHERE SEQUENCE_OWNER = " + literal(schema)
                + " ORDER BY SEQUENCE_NAME";
    }

    /**
     * {@code LAST_NUMBER} 是<b>已经写进磁盘的那个号</b>，不是严格意义上的「下一个」。
     *
     * <h2>它会偏大，而偏大正是我们要的方向</h2>
     * 序列默认带 {@code CACHE 20}：Oracle 一次预分配一整段放进内存，只把段尾之后的
     * 那个数字写进数据字典。真机实测（23ai，起始 100、步长 7、取了三次）——
     * 真实的下一个号是 121，而 {@code LAST_NUMBER} 给的是 240，中间隔着 119 个。
     *
     * <p>照 240 恢复会跳过 121…233。那一段号在原库上只存在于实例的内存里，
     * 实例一重启同样作废，所以跳掉它们不损失什么。
     *
     * <p>反过来才是灾难：起始值取小了，恢复出来的序列会把已经用过的号<b>再发一遍</b>，
     * 而这不会在恢复时报错，要等到某次插入撞上主键冲突。两个方向的代价差着数量级。
     */
    @Override
    public String sequenceAttributesQuery(String schema) {
        return "SELECT SEQUENCE_NAME, TO_CHAR(LAST_NUMBER), TO_CHAR(INCREMENT_BY),"
                + " TO_CHAR(MIN_VALUE), TO_CHAR(MAX_VALUE),"
                + " CASE WHEN CYCLE_FLAG = 'Y' THEN 1 ELSE 0 END"
                + " FROM ALL_SEQUENCES WHERE SEQUENCE_OWNER = " + literal(schema)
                + " ORDER BY SEQUENCE_NAME";
    }

    @Override
    public String viewDefinitionQuery(String schema, String view) {
        return "SELECT TEXT FROM ALL_VIEWS"
                + " WHERE OWNER = " + literal(schema)
                + " AND VIEW_NAME = " + literal(view);
    }

    /**
     * 触发器体是 PL/SQL，模板得给一段能真的编译过的。
     *
     * <p>{@code BEGIN} 和 {@code END} 之间必须至少有一条语句——空的过不了编译，
     * 所以放一条 {@code NULL;}（PL/SQL 的空操作），用户在它上面改。
     */
    /**
     * Oracle 有 {@code CREATE OR REPLACE TRIGGER}，改触发器不必先删——
     * 少了「中间一段时间触发器不存在」那个窗口。
     */
    @Override
    public String createTriggerDdl(String schema, String table, String triggerName,
                                   com.plainly.driver.meta.DbObjects.TriggerTiming timing,
                                   com.plainly.driver.meta.DbObjects.TriggerEvent event,
                                   String body) {
        return "CREATE OR REPLACE TRIGGER " + qualify(schema, triggerName) + "\n"
                + timing.name() + " " + event.name() + " ON " + qualify(schema, table) + "\n"
                + "FOR EACH ROW\n"
                + body;
    }

    /** PL/SQL 的 BEGIN...END 之间必须至少有一条语句，空的过不了编译，所以放一条 NULL;。 */
    @Override
    public String triggerBodyTemplate(com.plainly.driver.meta.DbObjects.TriggerEvent event) {
        return "BEGIN\n    NULL; -- " + rowRefHint(event) + "\nEND;";
    }

    /**
     * 执行计划要两条语句：先 {@code EXPLAIN PLAN FOR ...}，再查 {@code PLAN_TABLE}。
     * 这个接口只能给一条，所以如实说不支持，而不是发一条跑不出计划的语句。
     */
    @Override
    public String explainQuery(String sql) {
        return null;
    }

    // ------------------------------------------------------------------ 库级

    /**
     * Oracle 的 schema 就是用户，没有独立的「建 schema」这回事。
     *
     * <p>{@code CREATE SCHEMA} 在 Oracle 里存在，但它<b>不建 schema</b>——
     * 它只是在一条语句里批量建表和视图，schema 必须已经存在。真正要新开一个，
     * 得 {@code CREATE USER} 再加一串 {@code GRANT} 和表空间配额，
     * 需要 DBA 权限，而且授多少权限是环境策略问题，不该由一个客户端替人决定。
     */
    @Override
    public String schemaCreationUnsupportedReason() {
        return "Oracle 的模式就是用户：新建一个模式等于 CREATE USER 加一串授权和表空间配额，"
                + "要 DBA 权限，授权范围也得由你们的规范决定。请让 DBA 建好用户后再在这里连接。";
    }

    @Override
    public String truncateNote() {
        return "TRUNCATE 在 Oracle 是 DDL：执行即隐式提交，无法回滚，也不进 undo；"
                + "高水位线重置、空间被回收（除非加 REUSE STORAGE）；"
                + "被启用状态的外键引用着的表会直接报 ORA-02266，先禁用约束才能清。";
    }

    /** Oracle 的 DDL 逐条隐式提交，一批跑到一半失败，前面的已经生效且撤不回来。 */
    @Override
    public boolean supportsTransactionalDdl() {
        return false;
    }
}
