package com.plainly.driver.jdbc;

import com.plainly.driver.ConnectionConfig;
import com.plainly.driver.DbType;
import com.plainly.driver.SqlDialect;
import com.plainly.driver.ddl.ColumnDraft;
import com.plainly.driver.ddl.TableChange;
import com.plainly.driver.meta.DbObjects.ObjectKind;
import com.plainly.driver.meta.DbObjects.TriggerEvent;
import com.plainly.driver.meta.DbObjects.TriggerTiming;
import com.plainly.driver.jdbc.dialect.Dialects;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.List;
import java.util.Locale;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * 人大金仓 / OceanBase / GaussDB 这三家，离线能验的那一部分。
 *
 * <h2>这里验的是「写错了只在运行时才炸」的那几样</h2>
 * URL 前缀、驱动类名、方言挑对没有——这三样在编译期完全看不出问题，
 * 真连库的时候才报「No suitable driver」或者一堆语法错。
 *
 * <p><b>验不了的是精度和真实语法。</b>本项目的准入门槛是精度一致性检查
 * 在真机上跑通。GaussDB 已经在 openGauss 5.0.0 上跑过了（21 通过 / 0 不通过 /
 * 1 项厂商行为），金仓和 OceanBase 还没有实例，于是在 {@link DbType} 里
 * 如实标着「未验证」——这一条也在下面钉住了，免得哪天有人顺手把那几个字去掉。
 */
class DomesticDbTest {

    // ------------------------------------------------------------------ 驱动

    @Test
    @DisplayName("驱动类都在 classpath 上，且名字写对了")
    void driverClassesResolve() throws Exception {
        for (DbType type : new DbType[] {DbType.KINGBASE, DbType.OCEANBASE, DbType.GAUSSDB}) {
            assertFalse(type.driverClass().isBlank(), type + " 没写驱动类");
            // 名字写错的话，这一行会抛 ClassNotFoundException——
            // 而在产品里，那要等用户点「连接」才会发生
            assertNotNull(Class.forName(type.driverClass()), type + " 的驱动类加载不了");
        }
    }

    /**
     * openGauss 的驱动有两个变体，挑错那个会出大事。
     *
     * <p>不带 {@code -og} 后缀的那个把类放在 {@code org.postgresql} 包下，
     * 注册的驱动类也叫 {@code org.postgresql.Driver}——和真正的 PostgreSQL 驱动
     * <b>同名</b>。两个 jar 一起在 classpath 上时，用哪个取决于谁先被加载：
     * 连 PG 可能走成 openGauss 的驱动，反之亦然，而且不会有任何报错。
     */
    @Test
    @DisplayName("GaussDB 用的是 org.opengauss 那个变体，不和 PostgreSQL 驱动抢类名")
    void gaussDriverDoesNotClashWithPostgres() throws Exception {
        assertEquals("org.opengauss.Driver", DbType.GAUSSDB.driverClass());
        Class<?> gauss = Class.forName("org.opengauss.Driver");
        Class<?> postgres = Class.forName(DbType.POSTGRESQL.driverClass());
        assertFalse(gauss.equals(postgres), "两家的驱动类不能是同一个");
    }

    // ------------------------------------------------------------------ URL

    @Test
    @DisplayName("URL 前缀各家都对")
    void urlPrefixes() {
        assertTrue(url(DbType.KINGBASE, "h", 54321, "app")
                .startsWith("jdbc:kingbase8://h:54321/"), url(DbType.KINGBASE, "h", 54321, "app"));
        assertTrue(url(DbType.OCEANBASE, "h", 2881, "app")
                .startsWith("jdbc:oceanbase://h:2881/"), url(DbType.OCEANBASE, "h", 2881, "app"));
        // 是 opengauss 不是 postgresql——驱动是 pgjdbc 的分支，但 URL 前缀跟着包名走
        assertTrue(url(DbType.GAUSSDB, "h", 5432, "app")
                .startsWith("jdbc:opengauss://h:5432/"), url(DbType.GAUSSDB, "h", 5432, "app"));
    }

    @Test
    @DisplayName("库名留空时给一个连得上的默认值，而不是拼出斜杠结尾的空库名")
    void blankDatabaseFallsBack() {
        assertTrue(url(DbType.KINGBASE, "h", 54321, "").endsWith("/test"),
                url(DbType.KINGBASE, "h", 54321, ""));
        assertTrue(url(DbType.GAUSSDB, "h", 5432, "").endsWith("/postgres"),
                url(DbType.GAUSSDB, "h", 5432, ""));
    }

    // ------------------------------------------------------------------ 方言

    @Test
    @DisplayName("金仓和 GaussDB 走 PostgreSQL 那一套")
    void postgresFamilyDialects() {
        assertTrue(Dialects.forType(DbType.KINGBASE) instanceof Dialects.PostgresDialect);
        assertTrue(Dialects.forType(DbType.GAUSSDB) instanceof Dialects.PostgresDialect);
        // 引号是最直观的判据：PG 系用双引号，MySQL 系用反引号
        assertEquals("\"t\"", Dialects.forType(DbType.KINGBASE).quote("t"));
        assertEquals("\"t\"", Dialects.forType(DbType.GAUSSDB).quote("t"));
    }

    @Test
    @DisplayName("OceanBase 走 MySQL 那一套（默认的 MySQL 兼容模式）")
    void oceanBaseUsesMySqlDialect() {
        SqlDialect dialect = Dialects.forType(DbType.OCEANBASE);
        assertTrue(dialect instanceof Dialects.MySqlDialect);
        assertEquals("`t`", dialect.quote("t"));
    }

    // -------------------------------------------------------------- 自增写法

    /**
     * openGauss 的内核停在 PG 9.2，identity 列是 PG 10 才有的。
     *
     * <p>发 {@code GENERATED BY DEFAULT AS IDENTITY} 过去会得到
     * {@code syntax error at or near "BY"}——而「新建一张带自增主键的表」
     * 是最常做的一步，等于这条路整个不通。实测于 openGauss 5.0.0。
     *
     * <p>这个断言钉的是<b>别再退回去</b>：GaussDialect 继承 PostgresDialect，
     * 哪天有人觉得「它俩没差别」把覆写删掉，这里会红。
     */
    @Test
    @DisplayName("GaussDB 的自增列用 serial，不用 PG 10 的 identity")
    void gaussUsesSerialNotIdentity() {
        String ddl = Dialects.forType(DbType.GAUSSDB)
                .createTableDdl("public", "t", List.of(autoId("BIGINT")), List.of("id"));
        assertFalse(ddl.toUpperCase(Locale.ROOT).contains("AS IDENTITY"),
                "openGauss 不认 identity 写法：" + ddl);
        assertTrue(ddl.contains("bigserial"), ddl);

        assertTrue(Dialects.forType(DbType.GAUSSDB)
                .createTableDdl("public", "t", List.of(autoId("INTEGER")), List.of("id"))
                .contains("serial"), "INTEGER 也要映射成 serial");
    }

    /**
     * serial 是伪类型，非空和默认值已经含在里面了。
     *
     * <p>父类那段会无条件补 {@code NULL}/{@code NOT NULL} 和 {@code DEFAULT}，
     * 补上去服务端会报 {@code conflicting NULL/NOT NULL declarations} 或者
     * {@code multiple default values specified}——建表整个失败。
     * 两条都是在 openGauss 5.0.0 上实测出来的。
     */
    @Test
    @DisplayName("serial 列后面不再补 NULL / NOT NULL / DEFAULT")
    void serialCarriesItsOwnNullabilityAndDefault() {
        ColumnDraft id = autoId("BIGINT");
        id.setDefaultValue("5");
        String ddl = Dialects.forType(DbType.GAUSSDB)
                .createTableDdl("public", "t", List.of(id), List.of("id"));
        String line = ddl.lines().filter(l -> l.contains("bigserial")).findFirst().orElse("");
        assertFalse(line.toUpperCase(Locale.ROOT).contains("NULL"), line);
        assertFalse(line.toUpperCase(Locale.ROOT).contains("DEFAULT"), line);
    }

    /**
     * 推进自增计数器只能走 {@code setval}，而且第三个参数不能省。
     *
     * <p>父类的 {@code ALTER TABLE ... ALTER COLUMN ... RESTART WITH} 是 identity 语法，
     * 退一步的 {@code ALTER SEQUENCE ... RESTART} openGauss 5.0.0 也明说
     * {@code not yet supported}。
     *
     * <p>{@code setval(seq, n)} 的意思是「已经发到 n 了」，下一个发 n+1；
     * 而调用方传进来的 {@code next} 是<b>下一个要发的值</b>。漏掉 {@code false}
     * 会白白跳过一个号——不报错、不丢数据，正因如此才更难发现。
     */
    @Test
    @DisplayName("GaussDB 推进自增用 setval，且带 false 不多跳一个")
    void gaussRestartUsesSetval() {
        String sql = Dialects.forType(DbType.GAUSSDB)
                .restartAutoIncrementDdl("public", "t", "id", 9);
        assertNotNull(sql);
        assertTrue(sql.contains("setval"), sql);
        assertFalse(sql.toUpperCase(Locale.ROOT).contains("ALTER COLUMN"), sql);
        assertFalse(sql.toUpperCase(Locale.ROOT).contains("ALTER SEQUENCE"), sql);
        assertTrue(sql.contains("false"), "少了第三个参数，下一个值会多跳一个：" + sql);
    }

    /**
     * 往已有表上加自增列：openGauss 连 {@code ADD COLUMN ... bigserial} 都不让，
     * 只能把 serial 拆成「建序列 + 设默认值 + 回填」。
     *
     * <p>盯住的是<b>回填那一步</b>：默认值只对之后插入的行生效，已有行会留 NULL。
     * 真 PostgreSQL 上加 identity 列会重写整表、把已有行也编上号，
     * 少了回填就是两家行为不一致，而且不当场报错。
     */
    @Test
    @DisplayName("GaussDB 加自增列走序列，并且回填已有行")
    void gaussAddAutoIncrementColumnBackfills() {
        List<String> sqls = new ArrayList<>();
        Dialects.forType(DbType.GAUSSDB)
                .ddlFor("public", "t", new TableChange.AddColumn(autoId("BIGINT"), null))
                .forEach(x -> sqls.add(x.sql()));
        String all = String.join(String.valueOf((char) 10), sqls);

        assertFalse(all.contains("bigserial"), "ADD COLUMN 不能用 serial：" + all);
        assertTrue(sqls.stream().anyMatch(x -> x.startsWith("CREATE SEQUENCE")), all);
        assertTrue(sqls.stream().anyMatch(x -> x.contains("SET DEFAULT nextval")), all);
        assertTrue(sqls.stream().anyMatch(x -> x.startsWith("UPDATE") && x.contains("IS NULL")),
                "少了回填，已有行会留 NULL：" + all);
        assertTrue(sqls.stream().anyMatch(x -> x.contains("OWNED BY")),
                "少了 OWNED BY，删列之后序列会留下来：" + all);

        // 回填必须排在 SET NOT NULL 前面，否则那一条会被已有行的 NULL 顶回来
        int backfill = indexOfMatch(sqls, "UPDATE");
        int notNull = indexOfMatch(sqls, "SET NOT NULL");
        assertTrue(backfill >= 0 && notNull >= 0 && backfill < notNull,
                "回填要排在 SET NOT NULL 之前：" + all);
    }

    private static int indexOfMatch(List<String> sqls, String needle) {
        for (int i = 0; i < sqls.size(); i++) {
            if (sqls.get(i).contains(needle)) {
                return i;
            }
        }
        return -1;
    }

    // -------------------------------------------------------------- 触发器

    /**
     * 挂载子句：{@code EXECUTE FUNCTION} 是 PG 11 才有的同义写法。
     *
     * <p>老写法 {@code EXECUTE PROCEDURE} 从 PG 7 用到今天，PG 16 也仍然接受，
     * 所以这不是「退而求其次」，而是两边都认的那一个。
     */
    @Test
    @DisplayName("GaussDB 挂触发器用 EXECUTE PROCEDURE")
    void gaussTriggerUsesExecuteProcedure() {
        String ddl = Dialects.forType(DbType.GAUSSDB)
                .createTriggerDdl("public", "t", "tg", TriggerTiming.AFTER,
                        TriggerEvent.INSERT, null);
        assertTrue(ddl.contains("EXECUTE PROCEDURE"), ddl);
        assertFalse(ddl.contains("EXECUTE FUNCTION"), ddl);
    }

    /**
     * openGauss 的驱动走扩展协议，一次只肯执行一条命令。
     *
     * <p>两条拼一起会被服务端挡回来：
     * {@code cannot insert multiple commands into a prepared statement}。
     * 真 PostgreSQL 上 pgjdbc 会替我们处理掉，所以那边一直没露出来。
     */
    @Test
    @DisplayName("GaussDB 把建函数和挂触发器拆成两条")
    void gaussSplitsTriggerScript() {
        SqlDialect g = Dialects.forType(DbType.GAUSSDB);
        String ddl = g.createTriggerDdl("public", "t", "tg", TriggerTiming.AFTER,
                TriggerEvent.INSERT, null);
        List<String> parts = g.triggerStatements(ddl);
        assertEquals(2, parts.size(), ddl);
        assertTrue(parts.get(0).startsWith("CREATE OR REPLACE FUNCTION"), parts.get(0));
        assertTrue(parts.get(1).startsWith("CREATE TRIGGER"), parts.get(1));

        // PostgreSQL 那边不拆：pgjdbc 自己会处理，拆了反而多一次往返
        assertEquals(1, Dialects.forType(DbType.POSTGRESQL).triggerStatements(ddl).size());
    }

    /**
     * 用户写的触发器体必须真的进到生成的函数里。
     *
     * <p>这一条原来是坏的：方言接了 {@code body} 参数却一个字都没用，
     * 生成的函数永远只是 {@code RETURN NEW}。表现是<b>触发器建得好好的、
     * 什么也不做</b>——比报错难发现得多，因为每一步看起来都成功了。
     *
     * <p>PG 家族都受影响，所以两家都钉住。
     */
    @Test
    @DisplayName("用户写的触发器体不会被丢掉")
    void triggerBodyIsNotDiscarded() {
        String body = "BEGIN" + (char) 10 + "    PERFORM 1;" + (char) 10
                + "    RETURN NEW;" + (char) 10 + "END;";
        for (DbType type : new DbType[] {DbType.POSTGRESQL, DbType.GAUSSDB}) {
            String ddl = Dialects.forType(type).createTriggerDdl("public", "t", "tg",
                    TriggerTiming.AFTER, TriggerEvent.INSERT, body);
            assertTrue(ddl.contains("PERFORM 1;"),
                    type + " 把用户写的触发器体丢掉了：" + ddl);
        }
    }

    /**
     * PG 的触发器体模板必须带 RETURN。
     *
     * <p>默认模板只有 {@code BEGIN ... END}，那是 MySQL 的形状。用在 plpgsql 里
     * 函数会返回 NULL，而 BEFORE 触发器返回 NULL 的含义是<b>丢弃这一行</b>——
     * 一个本意只想记条日志的触发器，会安静地把插入的数据吃掉。
     */
    @Test
    @DisplayName("PG 家族的触发器体模板带 RETURN")
    void postgresTriggerTemplateReturns() {
        for (DbType type : new DbType[] {DbType.POSTGRESQL, DbType.GAUSSDB}) {
            assertTrue(Dialects.forType(type).triggerBodyTemplate(TriggerEvent.INSERT)
                    .contains("RETURN NEW"), type.toString());
            assertTrue(Dialects.forType(type).triggerBodyTemplate(TriggerEvent.DELETE)
                    .contains("RETURN OLD"), type.toString());
        }
    }

    /**
     * 「修改触发器」打开时，编辑框里要填用户写的那段 plpgsql。
     *
     * <p>PostgreSQL 的 {@code information_schema.triggers.action_statement}
     * 只有一句 {@code EXECUTE FUNCTION f()}——逻辑在函数里，不在触发器上。
     * 照搬那一栏，用户看到的不是自己写的东西；而且存回去时那一句会被当成函数体
     * 塞进 {@code $$ ... $$}，把原来的逻辑顶掉，<b>不报错</b>。
     *
     * <p>所以要顺着 {@code pg_trigger.tgfoid} 取函数的 {@code prosrc}。
     */
    @Test
    @DisplayName("PG 家族读触发器体取的是函数源码，不是 EXECUTE FUNCTION 那一句")
    void postgresFamilyReadsFunctionSource() {
        for (DbType type : new DbType[] {DbType.POSTGRESQL, DbType.GAUSSDB, DbType.KINGBASE}) {
            String q = Dialects.forType(type).triggersQuery("public", "t");
            assertTrue(q.contains("prosrc"), type + " 读不到函数体：" + q);
            assertTrue(q.contains("tgfoid"), type + " 没顺着触发器找到那个函数：" + q);
            // 模式必须一起限定死，否则别的模式里的同名表会连出重复行
            assertTrue(q.contains("relnamespace"), type + " join 没限定模式：" + q);
        }
    }

    // ------------------------------------------------------- 金仓 V8R3 兼容

    /**
     * V8R3 的判据必须是<b>症状</b>，不能是版本号。
     *
     * <p>金仓的系统目录在 V8R6 改过名（{@code sys_catalog} → {@code pg_catalog}）。
     * 按版本号判断的话，格式一变就会把好连接拦下来；而「{@code pg_catalog} 查不到、
     * {@code sys_catalog} 查得到」是确凿的，除了这一种情况没有别的解释。
     *
     * <p>这条钉的是「别退回去按版本号判」——那种改动编译得过、单测也不一定红，
     * 要等某个客户的版本号格式不一样才炸。
     */
    @Test
    @DisplayName("V8R3 的判据靠查系统目录，不靠版本号")
    void legacyDetectionAsksTheServer() throws Exception {
        String src = java.nio.file.Files.readString(java.nio.file.Path.of(
                "src/main/java/com/plainly/driver/jdbc/KingbaseLegacy.java"));
        int at = src.indexOf("static boolean detect(");
        assertTrue(at > 0, "detect 方法没了");
        String body = src.substring(at, src.indexOf("private static boolean canQuery", at));
        assertTrue(body.contains("pg_catalog.pg_namespace")
                        && body.contains("sys_catalog.sys_namespace"),
                "判据应当是查两套目录：" + body);
        assertFalse(body.contains("getDatabaseMajorVersion")
                        || body.contains("V008R") || body.contains("getDatabaseProductVersion"),
                "不能按版本号判：" + body);
    }

    /**
     * 只有金仓会走那条路。
     *
     * <p>接管元数据是件很重的事——它绕开驱动、自己发 SQL。漏到别的库上，
     * 那些库的元数据会安静地换一套来源，而且很难发现。
     */
    @Test
    @DisplayName("接管元数据只对金仓生效，别的库一行都不走")
    void legacyPathIsKingbaseOnly() throws Exception {
        String src = java.nio.file.Files.readString(java.nio.file.Path.of(
                "src/main/java/com/plainly/driver/jdbc/JdbcConnections.java"));
        int at = src.indexOf("private static boolean needsLegacyKingbase");
        assertTrue(at > 0, "needsLegacyKingbase 没了");
        String body = src.substring(at, src.indexOf("}", src.indexOf("return", at)));
        assertTrue(body.contains("DbType.KINGBASE"), "没按类型收口：" + body);
    }

    // -------------------------------------------------------------- 系统目录

    /**
     * {@code pg_sequences} 是 <b>PG 10</b> 才加的视图，9.2 内核上不存在。
     *
     * <p>三条查询都用到它，少改一条就是「序列列表能看、备份却查不出来」
     * 这种一半好一半坏的状态。
     */
    @Test
    @DisplayName("GaussDB 的序列查询不碰 PG 10 才有的 pg_sequences")
    void gaussAvoidsPgSequencesView() {
        SqlDialect g = Dialects.forType(DbType.GAUSSDB);
        List<String> queries = List.of(
                g.sequencesQuery("public"),
                g.sequenceAttributesQuery("public"),
                g.objectDefinitionQuery(ObjectKind.SEQUENCE, "public", "s"));
        for (String q : queries) {
            assertNotNull(q);
            assertFalse(q.contains("pg_sequences"), "这里用不了 pg_sequences：" + q);
            assertTrue(q.contains("pg_sequence_parameters") || q.contains("pg_sequence_last_value"),
                    q);
        }
        // 备份那条的第二列必须是「下一个该发的号」，不能是建序列时的起始值
        assertTrue(g.sequenceAttributesQuery("public").contains("+ (pg_sequence_parameters"),
                "少加一个步长会让恢复出来的序列重发已经用过的号");
    }

    /** PostgreSQL 自己不受影响：它是 PG 10+，identity 是更好的写法。 */
    @Test
    @DisplayName("真正的 PostgreSQL 仍然用 identity，没被顺手改掉")
    void postgresKeepsIdentity() {
        String ddl = Dialects.forType(DbType.POSTGRESQL)
                .createTableDdl("public", "t", List.of(autoId("BIGINT")), List.of("id"));
        assertTrue(ddl.contains("GENERATED BY DEFAULT AS IDENTITY"), ddl);
    }

    private static ColumnDraft autoId(String type) {
        ColumnDraft d = ColumnDraft.added("id");
        d.setNativeType(type);
        d.setNullable(false);
        d.setAutoIncrement(true);
        return d;
    }

    // ------------------------------------------------------------------ 如实标注

    /**
     * 这一条守的是诚实。
     *
     * <p>三家都没有真实实例验过，界面上就必须说出来。去掉那几个字很容易——
     * 顺手改个显示名就没了，而用户会以为它和 MySQL 一样可靠。
     * 真机验过之后再删这个断言，连同显示名一起。
     */
    @Test
    @DisplayName("没在真机验过的，显示名里要如实标着「未验证」")
    void unverifiedTypesSaySo() {
        // GaussDB（openGauss 5.0.0）和金仓（V8R3）都已在真机上验过，
        // 见各自在 DbType 上的说明。只剩 OceanBase 还没有实例
        for (DbType type : new DbType[] {DbType.OCEANBASE}) {
            assertTrue(type.displayName().contains("未验证"),
                    type + " 还没在真实实例上验过，显示名里得说出来：" + type.displayName());
        }
    }

    private static String url(DbType type, String host, int port, String database) {
        return JdbcConnections.buildUrl(new ConnectionConfig()
                .setType(type).setHost(host).setPort(port).setDatabase(database));
    }
}
