package com.plainly.driver.jdbc;

import com.plainly.driver.DbType;
import com.plainly.driver.SqlDialect;
import com.plainly.driver.TypeCategory;
import com.plainly.driver.TypeNames;
import com.plainly.driver.ddl.ColumnDraft;
import com.plainly.driver.ddl.TableChange;
import com.plainly.driver.jdbc.dialect.Dialects;
import com.plainly.driver.meta.DbObjects.ColumnInfo;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Oracle 与达梦方言生成的 SQL。
 *
 * <h2>这套测试守的是什么</h2>
 * 手上没有真实的 Oracle 实例，所以这里守的<b>不是</b>「能连上」，
 * 而是那几处「写错了要到数据库那边才炸、且报错信息看不出原因」的语法：
 * DEFAULT 和 NOT NULL 的先后、改列必须合成一条 MODIFY、
 * 可空性不能重复声明、数据字典视图的名字。
 *
 * <p>另一半在 {@link OracleSyntaxSmokeTest} 里：那边把这里断言过的语句
 * <b>真的执行一遍</b>。两者缺一不可——只比字符串，拼错了括号也发现不了；
 * 只执行，跑在 H2 的兼容模式上又盖不住 Oracle 特有的约束。
 */
@DisplayName("Oracle / 达梦 · 方言")
class OracleDialectTest {

    private static final String SCHEMA = "SHOP";
    private static final String TABLE = "ORDERS";

    private static final SqlDialect ORACLE = Dialects.forType(DbType.ORACLE);
    private static final SqlDialect DM = Dialects.forType(DbType.DM);

    // ------------------------------------------------------------------ 自增列

    @Test
    @DisplayName("身份列子句必须排在 NOT NULL 之前——反过来 Oracle 直接报 ORA-03076")
    void identityComesBeforeInlineConstraints() {
        ColumnDraft id = ColumnDraft.added("id");
        id.setNativeType("NUMBER(19)");
        id.setNullable(false);
        id.setPrimaryKey(true);
        id.setAutoIncrement(true);

        String def = ORACLE.columnDefinition(id);

        // Oracle 的列定义语法是「列名 类型 [DEFAULT|身份列] [内联约束…]」，
        // NOT NULL 属于内联约束。原来把身份列放在最后，注释里还写着
        // 「Oracle 要求 identity 子句在列约束之后」——那句话是错的，
        // 在 Oracle 23ai 实例上直接报「列定义或内部约束条件中存在意外项 GENERATED」
        int identityAt = def.indexOf("GENERATED");
        int notNullAt = def.indexOf("NOT NULL");
        assertTrue(identityAt > 0, "应当带身份列子句：" + def);
        assertTrue(notNullAt > 0, "应当带 NOT NULL：" + def);
        assertTrue(identityAt < notNullAt, "身份列子句要排在 NOT NULL 前面：" + def);
    }

    @Test
    @DisplayName("自增列不能再带 DEFAULT——两个一起写同样报错")
    void identityExcludesDefault() {
        ColumnDraft id = ColumnDraft.added("id");
        id.setNativeType("NUMBER(19)");
        id.setNullable(false);
        id.setAutoIncrement(true);
        id.setDefaultValue("0");

        String def = ORACLE.columnDefinition(id);
        assertTrue(def.contains("GENERATED BY DEFAULT AS IDENTITY"), def);
        // 注意不能直接断言「不含 DEFAULT」——身份列子句本身就叫
        // GENERATED BY DEFAULT AS IDENTITY，那个词在里面。要防的是
        // 另外再冒出一个 DEFAULT <值> 子句，它和身份列互斥
        assertFalse(def.contains("DEFAULT 0"),
                "自增列的值由序列给，再写 DEFAULT 会被 Oracle 拒绝：" + def);
    }

    @Test
    @DisplayName("达梦用 IDENTITY(1, 1)，位置和 Oracle 一样在 NOT NULL 之前")
    void dmIdentityPlacement() {
        ColumnDraft id = ColumnDraft.added("id");
        id.setNativeType("BIGINT");
        id.setNullable(false);
        id.setAutoIncrement(true);

        String def = DM.columnDefinition(id);
        assertTrue(def.contains("IDENTITY(1, 1)"), def);
        assertFalse(def.contains("GENERATED"), "达梦不用 Oracle 那套写法：" + def);
        assertTrue(def.indexOf("IDENTITY") < def.indexOf("NOT NULL"), def);
    }

    // ------------------------------------------------------------------ 夹具

    private static ColumnInfo col(String name, String type, int precision, int scale,
                                  boolean nullable, String defaultValue) {
        return new ColumnInfo(name, type, TypeNames.categoryOf(type),
                precision, scale, nullable, false, false, defaultValue, "", 0);
    }

    private static ColumnDraft draft(String name, String type, int precision, int scale,
                                     boolean nullable, String defaultValue) {
        ColumnDraft d = ColumnDraft.of(col(name, type, precision, scale, nullable, defaultValue));
        return d;
    }

    private static String sqlOf(SqlDialect dialect, TableChange change) {
        List<SqlDialect.TableChangeSql> out = dialect.ddlFor(SCHEMA, TABLE, change);
        assertEquals(1, out.size(), "本用例期望正好一条语句，实得 " + out.size() + "：" + out);
        return out.get(0).sql();
    }

    // ------------------------------------------------------------------ 列定义

    @Nested
    @DisplayName("列定义")
    class ColumnDefinition {

        @Test
        @DisplayName("DEFAULT 排在 NOT NULL 前面")
        void defaultComesBeforeNotNull() {
            String sql = ORACLE.columnDefinition(draft("AMOUNT", "NUMBER", 38, 10, false, "0"));

            assertEquals("\"AMOUNT\" NUMBER(38,10) DEFAULT 0 NOT NULL", sql);

            // 反过来写在 Oracle 上是 ORA-00907，而且报的是「缺少右括号」，
            // 从错误信息完全看不出是顺序问题。所以这里把顺序本身钉死
            int defaultAt = sql.indexOf("DEFAULT");
            int notNullAt = sql.indexOf("NOT NULL");
            assertTrue(defaultAt > 0 && notNullAt > defaultAt,
                    "DEFAULT 必须在 NOT NULL 之前：" + sql);
        }

        @Test
        @DisplayName("可空列不写出 NULL——列本来就默认可空")
        void nullableColumnOmitsTheKeyword() {
            String sql = ORACLE.columnDefinition(draft("NOTE", "VARCHAR2", 255, 0, true, null));
            assertEquals("\"NOTE\" VARCHAR2(255)", sql);
        }

        @Test
        @DisplayName("空白的默认值不生成 DEFAULT 子句")
        void blankDefaultProducesNoClause() {
            String sql = ORACLE.columnDefinition(draft("NOTE", "VARCHAR2", 255, 0, true, "   "));
            assertFalse(sql.contains("DEFAULT"),
                    "只有空白的默认值会拼出一条 `DEFAULT ` 结尾的语法错误：" + sql);
        }
    }

    // ------------------------------------------------------------------ 改列

    @Nested
    @DisplayName("改列")
    class Modify {

        @Test
        @DisplayName("类型、默认值、可空性合成一条 MODIFY")
        void allAspectsCollapseIntoOneStatement() {
            ColumnInfo from = col("AMOUNT", "NUMBER", 10, 2, true, null);
            ColumnDraft to = draft("AMOUNT", "NUMBER", 38, 10, false, "0");

            assertEquals("ALTER TABLE \"SHOP\".\"ORDERS\" MODIFY "
                            + "(\"AMOUNT\" NUMBER(38,10) DEFAULT 0 NOT NULL)",
                    sqlOf(ORACLE, new TableChange.ModifyColumn(from, to)));
        }

        @Test
        @DisplayName("可空性没变就不写它——重复声明是 ORA-01442 / ORA-01451")
        void unchangedNullabilityIsNotRestated() {
            ColumnInfo from = col("AMOUNT", "NUMBER", 10, 2, false, null);
            ColumnDraft to = draft("AMOUNT", "NUMBER", 38, 10, false, null);

            String sql = sqlOf(ORACLE, new TableChange.ModifyColumn(from, to));
            assertEquals("ALTER TABLE \"SHOP\".\"ORDERS\" MODIFY (\"AMOUNT\" NUMBER(38,10))", sql);
            assertFalse(sql.contains("NOT NULL"),
                    "往本来就非空的列上再打一次 NOT NULL 是 ORA-01442：" + sql);
        }

        @Test
        @DisplayName("清掉默认值写成 DEFAULT NULL，不是 DROP DEFAULT")
        void droppingADefaultIsSpelledDefaultNull() {
            ColumnInfo from = col("NOTE", "VARCHAR2", 255, 0, true, "'x'");
            ColumnDraft to = draft("NOTE", "VARCHAR2", 255, 0, true, null);

            assertEquals("ALTER TABLE \"SHOP\".\"ORDERS\" MODIFY (\"NOTE\" DEFAULT NULL)",
                    sqlOf(ORACLE, new TableChange.ModifyColumn(from, to)));
        }

        @Test
        @DisplayName("什么都没变就不产出语句")
        void noChangeProducesNothing() {
            ColumnInfo from = col("NOTE", "VARCHAR2", 255, 0, true, null);
            ColumnDraft to = draft("NOTE", "VARCHAR2", 255, 0, true, null);
            assertTrue(ORACLE.ddlFor(SCHEMA, TABLE, new TableChange.ModifyColumn(from, to))
                    .isEmpty());
        }

        @Test
        @DisplayName("改列名用 RENAME COLUMN，不是标准的 ALTER COLUMN ... RENAME TO")
        void renameUsesOracleSpelling() {
            ColumnInfo from = col("NOTE", "VARCHAR2", 255, 0, true, null);
            ColumnDraft to = draft("NOTE", "VARCHAR2", 255, 0, true, null);
            to.setName("REMARK");

            assertEquals("ALTER TABLE \"SHOP\".\"ORDERS\" RENAME COLUMN \"NOTE\" TO \"REMARK\"",
                    sqlOf(ORACLE, new TableChange.RenameColumn(from, to)));
        }

        @Test
        @DisplayName("加列要带括号：ALTER TABLE ... ADD (...)")
        void addColumnIsParenthesised() {
            ColumnDraft added = draft("MEMO", "VARCHAR2", 100, 0, true, null);
            assertEquals("ALTER TABLE \"SHOP\".\"ORDERS\" ADD (\"MEMO\" VARCHAR2(100))",
                    sqlOf(ORACLE, new TableChange.AddColumn(added, null)));
        }
    }

    // ------------------------------------------------------------------ 分页

    @Nested
    @DisplayName("分页")
    class Paging {

        @Test
        @DisplayName("OFFSET / FETCH 的写法")
        void offsetFetchSpelling() {
            assertEquals("FETCH NEXT 100 ROWS ONLY", ORACLE.limitOffset(100, 0));
            assertEquals("OFFSET 200 ROWS FETCH NEXT 100 ROWS ONLY", ORACLE.limitOffset(100, 200));
            assertEquals("OFFSET 200 ROWS", ORACLE.limitOffset(0, 200));
        }

        @Test
        @DisplayName("两个参数都不给时返回空串，免得计数语句尾巴上挂一段分页")
        void noArgumentsMeansNoClause() {
            assertEquals("", ORACLE.limitOffset(0, 0));
        }

        @Test
        @DisplayName("带筛选的计数不会带上分页子句")
        void filteredCountHasNoPagingClause() {
            List<ColumnInfo> columns = List.of(col("AMOUNT", "NUMBER", 38, 10, true, null));
            com.plainly.driver.query.FilterSpec filter = new com.plainly.driver.query.FilterSpec(
                    List.of(new com.plainly.driver.query.FilterSpec.Condition(
                            com.plainly.driver.query.FilterSpec.Combiner.AND, "AMOUNT",
                            com.plainly.driver.query.FilterSpec.Operator.EQ, "1", null)),
                    List.of());

            String sql = ORACLE.countRows(SCHEMA, TABLE, filter, columns).sql().trim();
            assertEquals("SELECT COUNT(*) FROM \"SHOP\".\"ORDERS\" WHERE \"AMOUNT\" = ?", sql);
            assertFalse(sql.contains("OFFSET"), "计数语句里不该有分页子句：" + sql);
            assertFalse(sql.contains("FETCH"), "计数语句里不该有分页子句：" + sql);
        }
    }

    // ------------------------------------------------------------------ 元数据与能力

    @Nested
    @DisplayName("数据字典与能力边界")
    class Capabilities {

        @Test
        @DisplayName("触发器查 ALL_TRIGGERS，不是 INFORMATION_SCHEMA")
        void triggersComeFromTheDataDictionary() {
            String sql = ORACLE.triggersQuery(SCHEMA, TABLE);
            assertTrue(sql.contains("ALL_TRIGGERS"), sql);
            assertFalse(sql.contains("INFORMATION_SCHEMA"),
                    "Oracle 没有 INFORMATION_SCHEMA，这条会直接报表不存在：" + sql);
            assertTrue(sql.contains("TABLE_OWNER = 'SHOP'"),
                    "归属列叫 TABLE_OWNER，不是 schema：" + sql);
        }

        @Test
        @DisplayName("视图定义查 ALL_VIEWS")
        void viewDefinitionComesFromAllViews() {
            String sql = ORACLE.viewDefinitionQuery(SCHEMA, "V_ORDERS");
            assertTrue(sql.contains("ALL_VIEWS"), sql);
            assertTrue(sql.contains("OWNER = 'SHOP'"), sql);
        }

        @Test
        @DisplayName("执行计划要两条语句，所以如实说不支持")
        void explainIsHonestlyUnsupported() {
            assertNull(ORACLE.explainQuery("SELECT 1 FROM DUAL"),
                    "给一条跑不出计划的语句，比说不支持更糟");
        }

        @Test
        @DisplayName("Oracle 建不了模式，并且说清为什么")
        void schemaCreationIsRefusedWithAReason() {
            String reason = ORACLE.schemaCreationUnsupportedReason();
            assertNotNull(reason);
            assertTrue(reason.contains("CREATE USER"),
                    "解释里得说清模式就是用户，不然用户不知道该找谁：" + reason);
        }

        @Test
        @DisplayName("DDL 不参与事务——不能承诺一个做不到的回滚")
        void ddlIsNotTransactional() {
            assertFalse(ORACLE.supportsTransactionalDdl());
        }

        @Test
        @DisplayName("触发器模板里有一条 NULL;——PL/SQL 的空块编译不过")
        void triggerTemplateCompiles() {
            String template = ORACLE.createTriggerTemplate(SCHEMA, TABLE, "T_AUDIT");
            assertTrue(template.contains("NULL;"),
                    "BEGIN/END 之间至少要有一条语句，否则模板本身就编译不过：" + template);
        }

        @Test
        @DisplayName("COLUMN_DEF 的尾部空白被清掉，全空白算没有默认值")
        void defaultValueIsTrimmed() {
            assertEquals("'CNY'", ORACLE.normalizeDefault("'CNY'  \n", TypeCategory.STRING));
            assertNull(ORACLE.normalizeDefault("   \n", TypeCategory.STRING));
            assertNull(ORACLE.normalizeDefault(null, TypeCategory.STRING));
        }
    }

    // ------------------------------------------------------------------ 达梦

    @Nested
    @DisplayName("达梦与 Oracle 的差异")
    class Dameng {

        @Test
        @DisplayName("继承了 Oracle 的语法：改列还是一条 MODIFY，顺序也一样")
        void inheritsOracleSyntax() {
            ColumnInfo from = col("AMOUNT", "NUMBER", 10, 2, true, null);
            ColumnDraft to = draft("AMOUNT", "NUMBER", 38, 10, false, "0");

            assertEquals(sqlOf(ORACLE, new TableChange.ModifyColumn(from, to)),
                    sqlOf(DM, new TableChange.ModifyColumn(from, to)));
        }

        @Test
        @DisplayName("达梦能建模式，Oracle 不能")
        void damengCanCreateSchemas() {
            assertNull(DM.schemaCreationUnsupportedReason());
            assertEquals("CREATE SCHEMA \"SALES\"", DM.createSchemaDdl("SALES", null, null));
            assertNotNull(ORACLE.schemaCreationUnsupportedReason());
        }

        @Test
        @DisplayName("达梦有单语句 EXPLAIN")
        void damengHasExplain() {
            assertEquals("EXPLAIN SELECT 1", DM.explainQuery("SELECT 1"));
        }
    }

    // ------------------------------------------------------------------ 类型判定

    @Nested
    @DisplayName("Oracle 类型的语义判定")
    class Types {

        @Test
        @DisplayName("NUMBER 是精确数值——判错这一个就是静默丢精度")
        void numberIsExact() {
            assertEquals(TypeCategory.EXACT_NUMERIC, TypeNames.categoryOf("NUMBER"));
            assertEquals(TypeCategory.EXACT_NUMERIC, TypeNames.categoryOf("NUMBER(38,10)"));
            assertEquals(TypeCategory.EXACT_NUMERIC,
                    TypeCategories.of(java.sql.Types.NUMERIC, "NUMBER"));
        }

        @Test
        @DisplayName("BINARY_DOUBLE / BINARY_FLOAT 是浮点数，不是二进制数据")
        void binaryFloatsAreNotBlobs() {
            // 名字里的 BINARY 说的是「二进制浮点表示」。判成 BINARY 的话，
            // 整列会在网格里显示成 [BLOB 8 B 0x...]，看着像数据坏了
            assertEquals(TypeCategory.APPROX_NUMERIC, TypeNames.categoryOf("BINARY_DOUBLE"));
            assertEquals(TypeCategory.APPROX_NUMERIC, TypeNames.categoryOf("BINARY_FLOAT"));
            // 驱动给的是私有类型号，走不到 java.sql.Types 的分支，只能靠名字
            assertEquals(TypeCategory.APPROX_NUMERIC, TypeCategories.of(101, "BINARY_DOUBLE"));
        }

        @Test
        @DisplayName("RAW / LONG RAW 是二进制")
        void rawIsBinary() {
            assertEquals(TypeCategory.BINARY, TypeNames.categoryOf("RAW"));
            assertEquals(TypeCategory.BINARY, TypeNames.categoryOf("RAW(2000)"));
            assertEquals(TypeCategory.BINARY, TypeNames.categoryOf("LONG RAW"));
        }

        @Test
        @DisplayName("VARCHAR2 / NVARCHAR2 是字符串，括号里那个数是长度")
        void varchar2IsAString() {
            assertEquals(TypeCategory.STRING, TypeNames.categoryOf("VARCHAR2"));
            assertEquals(TypeCategory.STRING, TypeNames.categoryOf("NVARCHAR2"));
            assertEquals(TypeNames.LengthKind.STRING_LENGTH, TypeNames.lengthKindOf("VARCHAR2"));
            assertEquals(TypeNames.LengthKind.NUMERIC_PRECISION, TypeNames.lengthKindOf("NUMBER"));
        }

        @Test
        @DisplayName("类型目录把 NUMBER 排在最前，BINARY_DOUBLE 排在它后面")
        void catalogPutsExactNumericFirst() {
            List<String> catalog = TypeNames.catalogFor(DbType.ORACLE);
            assertEquals("NUMBER", catalog.get(0),
                    "顺手选到第一个应当是精确数值，而不是浮点");
            assertTrue(catalog.indexOf("NUMBER") < catalog.indexOf("BINARY_DOUBLE"));
        }
    }
}
