import com.plainly.core.db.Connections;
import com.plainly.driver.ConnectionConfig;
import com.plainly.driver.DbConnection;
import com.plainly.driver.DbType;
import com.plainly.driver.QueryResult;
import com.plainly.driver.SqlDialect;
import com.plainly.driver.ddl.ColumnDraft;
import com.plainly.driver.ddl.TableChange;
import com.plainly.driver.meta.DbObjects.ColumnInfo;
import com.plainly.driver.meta.DbObjects.TableStructure;

import java.util.ArrayList;
import java.util.List;

/**
 * openGauss 上建一张带自增主键的表，真的建得出来吗。
 *
 * <h2>这一条为什么值得单独验</h2>
 * openGauss 自报服务端版本 {@code 9.2.4}——PG 10 之后的东西一概没有，
 * 而我们的 PG 方言用的正是 PG 10 的 {@code GENERATED BY DEFAULT AS IDENTITY}。
 * 于是「新建一张带自增主键的表」这个最常见的动作会直接报
 * {@code syntax error at or near "BY"}。
 *
 * <p>走的是产品自己的 {@code createTableDdl} 和 {@code describeTable}，
 * 不手写 SQL——要验的正是方言挑对没有、以及<b>建出来之后还认不认得出自增</b>。
 * 后半句同样要紧：建表用 serial、回读却读不出自增标记的话，
 * 表结构界面上那个勾会莫名其妙地消失。
 *
 * <pre>
 * java -Dfile.encoding=UTF-8 -cp "plainly-app/target/plainly.jar;plainly-app/target/deps/*" ^
 *      tools/GaussIdentityProbe.java [主机] [端口] [用户] [口令] [库] [模式]
 * </pre>
 */
public class GaussIdentityProbe {

    private static int pass;
    private static int fail;

    public static void main(String[] args) {
        String host = args.length > 0 ? args[0] : "192.168.237.153";
        int port = args.length > 1 ? Integer.parseInt(args[1]) : 15432;
        String user = args.length > 2 ? args[2] : "gaussdb";
        String password = args.length > 3 ? args[3] : "Gaussdb@123";
        String database = args.length > 4 ? args[4] : "postgres";
        String schema = args.length > 5 ? args[5] : "public";

        ConnectionConfig cfg = new ConnectionConfig()
                .setName("gauss-identity").setType(DbType.GAUSSDB)
                .setHost(host).setPort(port)
                .setUser(user).setPassword(password).setDatabase(database);

        String table = "pl_identity_probe";
        try (DbConnection db = Connections.open(cfg)) {
            System.out.println("服务端：" + db.serverVersion());
            SqlDialect dialect = db.dialect();
            System.out.println("方言：  " + dialect.getClass().getSimpleName());

            drop(db, schema, table);

            // 和用户报的那张表形状一致
            List<ColumnDraft> drafts = new ArrayList<>();
            drafts.add(draft("id", "BIGINT", 0, false, true));
            drafts.add(draft("name", "VARCHAR", 255, true, false));
            drafts.add(draft("age", "INTEGER", 0, true, false));
            String ddl = dialect.createTableDdl(schema, table, drafts, List.of("id"));
            System.out.println();
            System.out.println(ddl);
            System.out.println();

            check("不再发 PG 10 的 identity 写法", !ddl.toUpperCase().contains("AS IDENTITY"), ddl);
            check("自增列用 serial 系列", ddl.contains("bigserial"), ddl);

            try {
                db.executeDdlBatch(List.of(ddl));
                check("建表成功", true, "");
            } catch (RuntimeException e) {
                check("建表成功", false, first(e));
                return;
            }

            // 回读：自增标记还在不在
            TableStructure st = db.describeTable(schema, table);
            ColumnInfo id = st.columns().stream()
                    .filter(c -> c.name().equals("id")).findFirst().orElse(null);
            check("回读得到 id 列", id != null, "结构里 " + st.columns().size() + " 列");
            if (id != null) {
                check("回读仍认得出自增", id.autoIncrement(),
                        "type=" + id.displayType() + " default=" + id.defaultValue());
                check("回读是非空的", !id.nullable(), "nullable=" + id.nullable());
            }
            check("主键读得回来", st.primaryKeyColumns().contains("id"),
                    String.valueOf(st.primaryKeyColumns()));

            // 真插两条，不给 id
            db.executeDdlBatch(List.of("INSERT INTO \"" + schema + "\".\"" + table + "\" (\"name\") VALUES ('甲')"));
            db.executeDdlBatch(List.of("INSERT INTO \"" + schema + "\".\"" + table + "\" (\"name\") VALUES ('乙')"));
            QueryResult r = db.execute("SELECT \"id\" FROM \"" + schema + "\".\"" + table + "\" ORDER BY \"id\"", 10);
            List<String> ids = new ArrayList<>();
            r.rows().forEach(row -> ids.add(row.get(0)));
            check("不给 id 也能插入，且自动编号", ids.equals(List.of("1", "2")), String.valueOf(ids));

            // 推进计数器：下一个应当正好是 9
            String restart = dialect.restartAutoIncrementDdl(schema, table, "id", 9);
            System.out.println();
            System.out.println(restart);
            System.out.println();
            check("推进语句不是 PG 10 的 RESTART 写法",
                    restart != null && !restart.toUpperCase().contains("ALTER COLUMN"), String.valueOf(restart));
            try {
                db.executeDdlBatch(List.of(restart));
                db.executeDdlBatch(List.of("INSERT INTO \"" + schema + "\".\"" + table + "\" (\"name\") VALUES ('丙')"));
                String next = db.execute("SELECT max(\"id\") FROM \"" + schema + "\".\"" + table + "\"", 1)
                        .rows().get(0).get(0);
                // 正好是 9 而不是 10——差一个说明 setval 的第三个参数漏了
                check("推进之后下一个正好是 9（不多跳一个）", "9".equals(next), "拿到 " + next);
            } catch (RuntimeException e) {
                check("推进计数器成功", false, first(e));
            }

            drop(db, schema, table);
            addColumnCase(db, dialect, schema);
        } catch (RuntimeException e) {
            check("连接", false, first(e));
        }

        System.out.println();
        System.out.println("通过 " + pass + " 项，失败 " + fail + " 项");
        if (fail > 0) {
            System.exit(1);
        }
    }

    /**
     * 往已有表上加自增列。
     *
     * <p>openGauss 连 {@code ADD COLUMN ... bigserial} 都不让，
     * 所以这一段走的是「建序列 + 设默认值 + 回填」那条路。
     * 最要紧的一条断言是<b>已有行也编上了号</b>——回填那一步漏掉不会当场报错。
     */
    private static void addColumnCase(DbConnection db, SqlDialect dialect, String schema) {
        String table = "pl_addcol_probe";
        drop(db, schema, table);
        String q = "\"" + schema + "\".\"" + table + "\"";
        db.executeDdlBatch(List.of("CREATE TABLE " + q + " (\"n\" VARCHAR(20))"));
        db.executeDdlBatch(List.of("INSERT INTO " + q + " (\"n\") VALUES ('旧一')"));
        db.executeDdlBatch(List.of("INSERT INTO " + q + " (\"n\") VALUES ('旧二')"));

        TableChange change = new TableChange.AddColumn(draft("id", "BIGINT", 0, false, true), null);
        List<String> sqls = new ArrayList<>();
        dialect.ddlFor(schema, table, change).forEach(x -> sqls.add(x.sql()));
        System.out.println();
        sqls.forEach(x -> System.out.println("  " + x));
        System.out.println();

        try {
            db.executeDdlBatch(sqls);
            check("往已有表上加自增列成功", true, "");
        } catch (RuntimeException e) {
            check("往已有表上加自增列成功", false, first(e));
            drop(db, schema, table);
            return;
        }

        QueryResult r = db.execute("SELECT \"id\" FROM " + q + " ORDER BY \"id\"", 10);
        List<String> ids = new ArrayList<>();
        r.rows().forEach(row -> ids.add(row.get(0)));
        // 回填那一步漏掉的话这里是两个 null——而且不会有任何报错
        check("已有的两行也编上了号（回填生效）", ids.equals(List.of("1", "2")), String.valueOf(ids));

        db.executeDdlBatch(List.of("INSERT INTO " + q + " (\"n\") VALUES ('新')"));
        String max = db.execute("SELECT max(\"id\") FROM " + q, 1).rows().get(0).get(0);
        check("新插入的行接着往下编号", "3".equals(max), "拿到 " + max);

        TableStructure st = db.describeTable(schema, table);
        ColumnInfo id = st.columns().stream()
                .filter(c -> c.name().equals("id")).findFirst().orElse(null);
        check("回读仍认得出自增", id != null && id.autoIncrement(),
                id == null ? "没读到" : "autoinc=" + id.autoIncrement());
        check("回读是非空的", id != null && !id.nullable(),
                id == null ? "没读到" : "nullable=" + id.nullable());

        drop(db, schema, table);
        // OWNED BY 生效的话，序列跟着表一起没了
        String left = db.execute(
                "SELECT count(*) FROM pg_class WHERE relname = '" + table + "_id_seq'", 1)
                .rows().get(0).get(0);
        check("表删掉后序列没有留下（OWNED BY 生效）", "0".equals(left), "还剩 " + left + " 个");
    }

    private static ColumnDraft draft(String name, String type, int precision,
                                     boolean nullable, boolean autoIncrement) {
        ColumnDraft d = ColumnDraft.added(name);
        d.setNativeType(type);
        d.setPrecision(precision);
        d.setNullable(nullable);
        d.setAutoIncrement(autoIncrement);
        return d;
    }

    private static void drop(DbConnection db, String schema, String table) {
        try {
            db.executeDdlBatch(List.of("DROP TABLE IF EXISTS \"" + schema + "\".\"" + table + "\""));
        } catch (RuntimeException ignored) {
            // 本来就没有
        }
    }

    private static String first(RuntimeException e) {
        String m = e.getMessage();
        return m == null ? e.toString() : m.split(String.valueOf((char) 10))[0];
    }

    private static void check(String what, boolean ok, String detail) {
        if (ok) {
            pass++;
            System.out.println("  " + what);
        } else {
            fail++;
            System.out.println("× " + what + "   实际：" + detail);
        }
    }
}
